name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Needed to push changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get complete history for merging

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/qgustavor/mkv-extract.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Try to merge - this will fail if there are conflicts
          git checkout repo
          git merge upstream/main --no-ff --no-edit --strategy-option=theirs

      - name: Push changes
        run: git push origin repo
